/**
 * Cloudflare Workers entry: the hosted variant of the Knowledge Hub MCP
 * server. The wiki travels inside the deploy artifact as a prebuilt JSON
 * bundle (run `npm run bundle` before `wrangler deploy`).
 *
 * Endpoint after deploy: https://<worker>.<account>.workers.dev/mcp
 */
import { McpAgent } from "agents/mcp";
import { buildServer } from "../src/server.js";
import { BundleWikiProvider, type WikiBundle } from "../src/bundle-provider.js";
// Generated by `npm run bundle` — not committed; build before deploy.
import bundleJson from "../dist/wiki-bundle.json";

export class KnowledgeHubMCP extends McpAgent {
  server = buildServer(new BundleWikiProvider(bundleJson as unknown as WikiBundle));

  async init() {
    // Tools and resources are registered in buildServer; nothing stateful here.
  }
}

export default KnowledgeHubMCP.serve("/mcp");
