/**
 * Cloudflare Workers entry: the hosted variant of the Knowledge Hub MCP
 * server. The wiki travels inside the deploy artifact as a prebuilt JSON
 * bundle (run `npm run bundle` before `wrangler deploy`).
 *
 * Endpoint after deploy: https://<worker>.<account>.workers.dev/mcp
 *
 * Also serves citation deep-links: /c/<slug>/<page> 302-redirects to the
 * source PDF opened at the cited page. Inline citations are rewritten to these
 * short links at serve time (see WikiStore.renderCitationNames), so a citation
 * in an answer is one click from its exact spot in the original report.
 */
import { McpAgent } from "agents/mcp";
import { buildServer } from "../src/server.js";
import { BundleWikiProvider, type WikiBundle } from "../src/bundle-provider.js";
// Generated by `npm run bundle` — not committed; build before deploy.
import bundleJson from "../dist/wiki-bundle.json";

// This worker's public origin. Citations are rewritten to absolute links here
// so they resolve in any client (a relative ../sources link does not).
const SELF_ORIGIN = "https://sandbox-knowledge-hub-mcp.bowen-9cc.workers.dev";
// jsDelivr serves the repo's PDFs inline, so a browser PDF viewer honours #page=N.
const CDN_ROOT = "https://cdn.jsdelivr.net/gh/bowen-0/sandbox-knowledge-hub@main";

const bundle = bundleJson as unknown as WikiBundle;

export class KnowledgeHubMCP extends McpAgent {
  server = buildServer(new BundleWikiProvider(bundle), { citationBaseUrl: SELF_ORIGIN });

  async init() {
    // Tools and resources are registered in buildServer; nothing stateful here.
  }
}

// slug -> repo-relative PDF path, from the source pages in the bundle. The
// English edition is citation-authoritative; fall back to the German original
// for sources without one.
const PDF_BY_SLUG: Map<string, string> = (() => {
  const m = new Map<string, string>();
  for (const p of bundle.pages ?? []) {
    if (p.type !== "source") continue;
    const fm = (p.frontmatter ?? {}) as Record<string, unknown>;
    const paths = [fm.path, fm.en_path].filter((x): x is string => typeof x === "string");
    const chosen = paths.find((x) => x.includes("/en/")) ?? paths.find((x) => x.includes("/de/"));
    if (chosen) m.set(p.slug, chosen.replace(/^\.\.\//, "wiki/"));
  }
  return m;
})();

const mcpHandler = KnowledgeHubMCP.serve("/mcp");

export default {
  fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    const { pathname } = new URL(request.url);
    // Citation deep-link: /c/<slug>[/<page>] -> the source PDF, at the cited page.
    const m = pathname.match(/^\/c\/([a-z0-9][a-z0-9-]*)(?:\/(\d+))?\/?$/i);
    if (m) {
      const pdf = PDF_BY_SLUG.get(m[1].toLowerCase());
      if (!pdf) return Promise.resolve(new Response(`Unknown source slug "${m[1]}"`, { status: 404 }));
      const target = `${CDN_ROOT}/${pdf}${m[2] ? `#page=${m[2]}` : ""}`;
      return Promise.resolve(new Response(null, { status: 302, headers: { Location: target } }));
    }
    return mcpHandler.fetch(request, env, ctx);
  },
};
